// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARCkrc-WwYPKwurLkrIGY-YbTJi2Lc8dI',
    appId: '1:59196752924:web:1f57e04b461ce15b784bd9',
    messagingSenderId: '59196752924',
    projectId: 'tomouno-8a1fc',
    authDomain: 'tomouno-8a1fc.firebaseapp.com',
    storageBucket: 'tomouno-8a1fc.firebasestorage.app',
    measurementId: 'G-SKM7S2XCG0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUYzbhP8GTy_k7_fiHpQgmZt6PJPbnmEk',
    appId: '1:59196752924:ios:a8be92229530ec01784bd9',
    messagingSenderId: '59196752924',
    projectId: 'tomouno-8a1fc',
    storageBucket: 'tomouno-8a1fc.firebasestorage.app',
    iosBundleId: 'com.example.editorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARCkrc-WwYPKwurLkrIGY-YbTJi2Lc8dI',
    appId: '1:59196752924:web:cfd8e244b188ff65784bd9',
    messagingSenderId: '59196752924',
    projectId: 'tomouno-8a1fc',
    authDomain: 'tomouno-8a1fc.firebaseapp.com',
    storageBucket: 'tomouno-8a1fc.firebasestorage.app',
    measurementId: 'G-E2WGJVYVB1',
  );
}
